name: New Deploy GKE cluster

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the GCP Project'
        required: true
      cluster_name:
        description: 'Name of GKE cluster'
        required: true
      subnet_name:
        description: 'Node subnet name'
        required: true
      region:
        description: 'Region of the GKE cluster'
        required: true
        type: choice
        options:
          - us-east4
      machine_type:
        description: '(Optional) Node machine type'
        required: false
        type: choice
        default: e2-small
        options:
          - ' '
          - e2-medium
          - c2-standard-8

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install gcloud beta components
        run: |
          chmod +x scripts/runner-bootstrap.sh
          ./scripts/runner-bootstrap.sh

      - name: Configure Variables
        id: configure-variables
        run: |
          POD_RANGE=$(gcloud compute networks subnets describe ${{ inputs.subnet_name }} --region=${{ inputs.region }} --format="get(secondaryIpRanges[0].rangeName)")
          SVC_RANGE=$(gcloud compute networks subnets describe ${{ inputs.subnet_name }} --region=${{ inputs.region }} --format="get(secondaryIpRanges[1].rangeName)")
          VPC_NAME=$(gcloud compute networks subnets describe ${{ inputs.subnet_name }} --region=${{ inputs.region }} --format="value(network)" | awk -F'/' '{print $NF}')
          echo "POD_RANGE=$POD_RANGE" >> $GITHUB_ENV
          echo "SVC_RANGE=$SVC_RANGE" >> $GITHUB_ENV
          echo "VPC_NAME=$VPC_NAME" >> $GITHUB_ENV

      - name: Create Static IP
        id: create-static-ip
        run: |
          gcloud config set project ${{ inputs.project_name }}
          gcloud compute addresses create api-proxy-ip-${{ inputs.cluster_name }} --region=${{ inputs.region }} --subnet=${{ inputs.subnet_name }}
          sleep 10
          PROXY_IP=$(gcloud compute addresses describe create api-proxy-ip-${{ inputs.cluster_name }} --region=${{ inputs.region }} --format="get(address)")
          echo "PROXY_IP=$PROXY_IP" >> $GITHUB_ENV


      - name: Deploy GKE cluster
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          CLUSTER_NAME: ${{ inputs.cluster_name }}
          REGION: ${{ inputs.region }}
          MACHINE_TYPE: ${{ inputs.machine_type }}
          SUBNET: ${{ inputs.subnet_name }}
          POD_RANGE: ${{ steps.configure-variables.outputs.POD_RANGE }}
          SVC_RANGE: ${{ steps.configure-variables.outputs.SVC_RANGE }}
          VPC_NAME: ${{ steps.configure-variables.outputs.VPC_NAME }}
        run: |
          chmod +x scripts/create-cluster.sh
          ./scripts/create-cluster.sh

      - name: Depoloy GKE Jump Host
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          CLUSTER_NAME: ${{ inputs.cluster_name }}
          REGION: ${{ inputs.region }}
          SUBNET: ${{ inputs.subnet_name }}
          GCP_SA: ${{ secrets.gcp_sa }}
        run: |
          chmod +x scripts/create-jump.sh
          ./scripts/create-jump.sh
              
      - name: SSH and Install Jump Tools 
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          CLUSTER_NAME: ${{ inputs.cluster_name }}
          REGION: ${{ inputs.region }}
          PROXY_IP: ${{ steps.create-static-ip.outputs.PROXY_IP }}
        run: |
          sleep 60
          chmod +x scripts/jump-bootstrap.sh
          ./scripts/jump-bootstrap.sh

          sleep 20

          chmod +x scripts/loadbalancer.sh
          ./scripts/loadbalancer.sh
            
          sleep 10
          
