name: Delete GCP VM

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the GCP Project'
        required: true
      vm_name:
        description: 'Name of the VM instance to delete'
        required: true
      zone:
        description: 'Zone of the VM instance to delete'
        required: true

jobs:
  delete:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ inputs.project_name }}

      - name: Delete VM instance
        run: |
          gcloud compute instances delete ${{ inputs.vm_name }} --zone=${{ inputs.zone }} --quiet
