name: Delete GCP VM

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the GCP Project'
        required: true
      vm_name:
        description: 'Name of the VM instance to delete'
        required: true

jobs:
  delete:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ inputs.project_name }}

      - name: Get VM Zone
        id: get-vm-zone
        run: |
          VM_ZONE=$(gcloud compute instances list \
            --filter="name=${{ inputs.vm_name }}" \
            --format="value(zone)")
        
          if [ -z "$VM_ZONE" ]; then
            echo "VM not found or you don't have permission to access it."
            exit 1
          fi

          echo "VM_ZONE=$VM_ZONE" >> $GITHUB_ENV

      - name: Delete VM instance
        env:
          VM_ZONE: ${{ env.VM_ZONE }}
        run: |
          
          gcloud compute instances delete ${{ inputs.vm_name }} --zone=${{ env.VM_ZONE }} --quiet
