name: Testing Scripts v2

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the GCP Project'
        required: true
      cluster_name:
        description: 'Name of GKE cluster'
        required: true
      subnet_name:
        description: 'Node subnet name'
        required: true
      region:
        description: 'Region of the GKE cluster'
        required: true
        type: choice
        options:
          - us-east4

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ inputs.project_name }}

      - name: Create Static IP
        id: static-ip
        run: |
          gcloud config set project ${{ inputs.project_name }}
          PROXY_IP=$(gcloud compute addresses describe api-proxy-ip-${{ inputs.cluster_name }} --region=${{ inputs.region }} --format="get(address)")
          echo "PROXY_IP=$PROXY_IP" >> $GITHUB_ENV

      - name: Create GKE Resources 
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          CLUSTER_NAME: ${{ inputs.cluster_name }}
          REGION: ${{ inputs.region }}
          PROXY_IP: ${{ env.PROXY_IP }}
        run: |
          gcloud config set project ${{ inputs.project_name }}
        
          chmod +x scripts/loadbalancer.sh
          ./scripts/loadbalancer.sh