name: Deploy GCP VM

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the GCP Project'
        required: true
      vm_name:
        description: 'Name of the VM instance to create'
        required: true
      zone:
        description: 'Zone of the VM instance to create'
        required: true
        type: choice
        options:
          - us-east4-a
          - us-east4-b
      machine_type:
        description: '(Optional) Machine type'
        required: true
        type: choice
        default: e2-small
        options:
          - e2-medium
          - c2-standard-8

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ inputs.project_name }}

      - name: Deploy VM instance
        run: |
          gcloud compute instances create ${{ inputs.vm_name }} \
            --project=${{ inputs.project_name }} \
            --zone=${{ inputs.zone }} \
            --machine-type=${{ inputs.machine_type }} \
            --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
            --maintenance-policy=MIGRATE \
            --provisioning-model=STANDARD \
            --service-account=${{ secrets.gcp_sa }} \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --tags=http-server,https-server \
            --create-disk=auto-delete=yes,boot=yes,device-name=${{ inputs.vm_name }},image=projects/debian-cloud/global/images/debian-12-bookworm-v20240611,mode=rw,size=10,type=projects/caramel-compass-356721/zones/us-east4-a/diskTypes/pd-balanced \
            --no-shielded-secure-boot \
            --shielded-vtpm \
            --shielded-integrity-monitoring \
            --labels=goog-ec-src=vm_add-gcloud \
            --reservation-affinity=any
